<?php

namespace Database\Seeders;

use App\Models\Level;
use Illuminate\Database\Seeder;

class LevelSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $levels = [
            [
                'id' => 1,
                'level_name' => 'Group Country Manager',
                'slug' => 'group-country-manager',
                'code' => 'GCM',
                'tire_level' => 1,
                'category' => 'executive',
                'isActive' => 1,
                'is_single_user' => 1,
            ],
            [
                'id' => 2,
                'level_name' => 'Chief Business Officer',
                'slug' => 'chief-business-officer',
                'code' => 'CBO',
                'tire_level' => 2,
                'category' => 'executive',
                'isActive' => 1,
                'is_single_user' => 1,
            ],
            [
                'id' => 3,
                'level_name' => 'Senior General Manager',
                'slug' => 'senior-general-manager',
                'code' => 'SGM',
                'tire_level' => 3,
                'category' => 'executive',
                'isActive' => 1,
                'is_single_user' => 0,
            ],
            [
                'id' => 4,
                'level_name' => 'General Manager',
                'slug' => 'general-manager',
                'code' => 'GM',
                'tire_level' => 4,
                'category' => 'executive',
                'isActive' => 1,
                'is_single_user' => 0,
            ],
            [
                'id' => 5,
                'level_name' => 'Deputy General Manager',
                'slug' => 'deputy-general-manager',
                'code' => 'DGM',
                'tire_level' => 5,
                'category' => 'executive',
                'isActive' => 1,
                'is_single_user' => 0,
            ],
            [
                'id' => 6,
                'level_name' => 'Assistant General Manager',
                'slug' => 'assistant-general-manager',
                'code' => 'AGM',
                'tire_level' => 6,
                'category' => 'executive',
                'isActive' => 1,
                'is_single_user' => 0,
            ],
            [
                'id' => 7,
                'level_name' => 'Senior National Sales Head',
                'slug' => 'senior-national-sales-head',
                'code' => 'SNSH',
                'tire_level' => 7,
                'category' => 'executive',
                'isActive' => 1,
                'is_single_user' => 0,
            ],
            [
                'id' => 8,
                'level_name' => 'National Sales Head',
                'slug' => 'national-sales-head',
                'code' => 'NSH',
                'tire_level' => 8,
                'category' => 'executive',
                'isActive' => 1,
                'is_single_user' => 0,
            ],
            [
                'id' => 9,
                'level_name' => 'Senior Head of Sales',
                'slug' => 'senior-head-of-sales',
                'code' => 'SHS',
                'tire_level' => 9,
                'category' => 'executive',
                'isActive' => 1,
                'is_single_user' => 0,
            ],
            [
                'id' => 10,
                'level_name' => 'Head of Sales',
                'slug' => 'head-of-sales',
                'code' => 'HOS',
                'tire_level' => 10,
                'category' => 'executive',
                'isActive' => 1,
                'is_single_user' => 0,
            ],
            [
                'id' => 11,
                'level_name' => 'Assistant Head of Sales',
                'slug' => 'assistant-head-of-sales',
                'code' => 'AHOS',
                'tire_level' => 11,
                'category' => 'executive',
                'isActive' => 1,
                'is_single_user' => 0,
            ],
            [
                'id' => 12,
                'level_name' => 'Senior Provincial Sales Manager',
                'slug' => 'senior-provincial-sales-manager',
                'code' => 'SPSM',
                'tire_level' => 12,
                'category' => 'executive',
                'isActive' => 1,
                'is_single_user' => 0,
            ],
            [
                'id' => 13,
                'level_name' => 'Provincial Manager',
                'slug' => 'provincial-manager',
                'code' => 'PM',
                'tire_level' => 13,
                'category' => 'executive',
                'isActive' => 1,
                'is_single_user' => 0,
            ],
            [
                'id' => 14,
                'level_name' => 'Senior Zonal Manager',
                'slug' => 'senior-zonal-manager',
                'code' => 'SZM',
                'tire_level' => 14,
                'category' => 'executive',
                'isActive' => 1,
                'is_single_user' => 0,
            ],
            [
                'id' => 15,
                'level_name' => 'Zonal Manager',
                'slug' => 'zonal-manager',
                'code' => 'ZM',
                'tire_level' => 15,
                'category' => 'executive',
                'isActive' => 1,
                'is_single_user' => 0,
            ],
            [
                'id' => 16,
                'level_name' => 'Deputy Zonal Manager',
                'slug' => 'deputy-zonal-manager',
                'code' => 'DZM',
                'tire_level' => 16,
                'category' => 'executive',
                'isActive' => 1,
                'is_single_user' => 0,
            ],
            [
                'id' => 17,
                'level_name' => 'Senior Regional Manager',
                'slug' => 'senior-regional-manager',
                'code' => 'SRM',
                'tire_level' => 17,
                'category' => 'executive',
                'isActive' => 1,
                'is_single_user' => 0,
            ],
            [
                'id' => 18,
                'level_name' => 'Regional Manager',
                'slug' => 'regional-manager',
                'code' => 'RM',
                'tire_level' => 18,
                'category' => 'executive',
                'isActive' => 1,
                'is_single_user' => 0,
            ],
            [
                'id' => 19,
                'level_name' => 'Assistant Regional Manager',
                'slug' => 'assistant-regional-manager',
                'code' => 'ARM',
                'tire_level' => 19,
                'category' => 'executive',
                'isActive' => 1,
                'is_single_user' => 0,
            ],
            [
                'id' => 20,
                'level_name' => 'Senior Branch Manager',
                'slug' => 'senior-branch-manager',
                'code' => 'SBM',
                'tire_level' => 20,
                'category' => 'executive',
                'isActive' => 1,
                'is_single_user' => 0,
            ],
            [
                'id' => 21,
                'level_name' => 'Branch Manager',
                'slug' => 'branch-manager',
                'code' => 'BM',
                'tire_level' => 21,
                'category' => 'executive',
                'isActive' => 1,
                'is_single_user' => 0,
            ],
            [
                'id' => 22,
                'level_name' => 'Assistant Branch Manager',
                'slug' => 'assistant-branch-manager',
                'code' => 'ABM',
                'tire_level' => 22,
                'category' => 'executive',
                'isActive' => 1,
                'is_single_user' => 0,
            ],
            [
                'id' => 23,
                'level_name' => 'Team Leader',
                'slug' => 'team-leader',
                'code' => 'TL',
                'tire_level' => 23,
                'category' => 'executive',
                'isActive' => 1,
                'is_single_user' => 0,
            ],
            [
                'id' => 24,
                'level_name' => 'Group Leader',
                'slug' => 'group-leader',
                'code' => 'GL',
                'tire_level' => 24,
                'category' => 'executive',
                'isActive' => 1,
                'is_single_user' => 0,
            ],
            [
                'id' => 25,
                'level_name' => 'Senior Consultant',
                'slug' => 'senior-consultant',
                'code' => 'SC',
                'tire_level' => 25,
                'category' => 'executive',
                'isActive' => 1,
                'is_single_user' => 0,
            ],
            [
                'id' => 26,
                'level_name' => 'Consultant',
                'slug' => 'consultant',
                'code' => 'C',
                'tire_level' => 26,
                'category' => 'executive',
                'isActive' => 1,
                'is_single_user' => 0,
            ],
        ];

        foreach ($levels as $level) {
            Level::updateOrCreate(
                ['id' => $level['id']],
                $level
            );
        }
    }
}
